name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stable:
    name: check (stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: make docs check-fast
      - if: github.event_name != 'pull_request'
        run: make check-extended
      - run: git diff --exit-code
      - run: test -z "$(git status --short)"

  msrv:
    name: check (1.85.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85.0
      - run: make check-msrv
